# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transfer_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='user',
            new_name='username',
        ),
    ]
