# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20161209_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
