# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20161209_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='username',
            new_name='user',
        ),
    ]
